version: '3'

services:
  apisum:
    image: apisum:0.0.2
    ports:
      - 8086:8086
    volumes:
      - ~/docker/redis:/urlshortner/logs
#    network_mode: host
  redis:
    image: redis:latest
    hostname: localhost
    ports:
      - 8088:6379
#    network_mode: host
