spring:
  application:
    name: Api-sum
  redis:
    database: 0
    host: localhost
    port: 8088
    timeout: 60000
datasource:
  sql-server:
    configurations:
      query-timeout: 60
      jdbcUrl: jdbc:postgresql://localhost:5432/postgres
      username: 'postgres'
      password: 'postgres'
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      validationQuery: SELECT 1
      connection-timeout: 60000
server:
  port : 8086
restTemplate:
  timeout: 60
  extern-service:
    url: 'https://tenpo-percentage.free.beeceptor.com/tenpo/percentage'
